#!/bin/sh
#
# Start 3288 linux service....
#

case "$1" in
	start)

		#Resize root filesystem to fit available disk space
		resize2fs /dev/mmcblk1p7

		# Mount debugfs
		mount -t debugfs none /sys/kernel/debug

		# bluetooth
		rkbt  /etc/bluetooth/BCM4335C0.hcd /dev/ttyS0 &

		# music
		/usr/bin/audioservice &

		echo performance > /sys/class/devfreq/ffa30000.gpu/governor
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

