#!/bin/sh
#
# Start 3399 linux service....
#

case "$1" in
	start)

		#Resize rootfs/userdata partition to fit available disk space
		resize2fs /dev/mmcblk1p8
		resize2fs /dev/mmcblk1p9

		# Mount debugfs
		mount -t debugfs none /sys/kernel/debug

		# bluetooth
		rkbt  /etc/bluetooth/bcm4354a1.hcd /dev/ttyS0 &

		# music
		/usr/bin/audioservice &

		echo performance > /sys/class/devfreq/ff9a0000.gpu/governor
		echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

