#!/bin/sh
#
# Start linux launcher...
#

case "$1" in
  start)
		# First boot configure
		if [[ -L /usr/lib/libmali.so && -f /usr/lib/libmali.so ]];
		then
			echo "libmali is linked."
		else
			echo "Fist boot: linking libmali."
			GPU_VERSION=$(cat /sys/devices/platform/*gpu/gpuinfo)
			if [ "$GPU_VERSION" != "Mali-T76x MP4 r1p0 0x0750" ];
			then
				ln -fs /usr/lib/libmali_eglfs_r0.so  /usr/lib/libmali.so
			else
				ln -fs /usr/lib/libmali_eglfs_r1.so  /usr/lib/libmali.so #rk3288w
			fi
		fi

		#Power manager
		/usr/bin/power_manager_service &

		printf "Starting launcher: "
		export LC_ALL='zh_CN.utf8'
		export QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS=/dev/input/event0
		export QT_QPA_EVDEV_KEYBOARD_PARAMETERS=/dev/input/event1:/dev/input/event2

		#for kmssink
		export QT_GSTREAMER_WINDOW_VIDEOSINK=kmssink

		#for Carmachine eglfs
		#/usr/bin/Carmachine -platform EGLFS -plugin EvdevTouch -plugin EvdevKeyboard &

		#for QLauncher eglfs
		/usr/local/QLauncher/QLauncher -platform EGLFS -plugin EvdevTouch -plugin EvdevKeyboard &
	;;
  stop)
		#killall CarMachine
		killall QLauncher
		printf "stop finished"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
