#!/bin/sh
#
# remount all the partitions in fstab after uevent handled....
#

case "$1" in
	start)
		mount -a
		;;
	stop)
		printf "stop finished"
        ;;
	*)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0

