#!/bin/sh
#
# Start ums and adb daemon service....
#

case "$1" in
  start)

	echo "Configuring USB gadget driver..."
	chmod 776 /usr/bin/usb_config
	UDC=`ls /sys/class/udc/| awk '{print $1}'`
	mount -t configfs none /sys/kernel/config
	mkdir /sys/kernel/config/usb_gadget/g1  -m 0770
	echo 0x2207 > /sys/kernel/config/usb_gadget/g1/idVendor
	mkdir /sys/kernel/config/usb_gadget/g1/strings/0x409   -m 0770
	sleep 1
	echo "0123456789ABCDEF" > /sys/kernel/config/usb_gadget/g1/strings/0x409/serialnumber
	echo "rockchip"  > /sys/kernel/config/usb_gadget/g1/strings/0x409/manufacturer
	echo "rk3xxx"  > /sys/kernel/config/usb_gadget/g1/strings/0x409/product

	mkdir /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0
	echo /dev/mmcblk0p1 > /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0/lun.0/file
	mkdir /sys/kernel/config/usb_gadget/g1/configs/c.1 -m 0770
	mkdir /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409 -m 0770
	echo 120 > /sys/kernel/config/usb_gadget/g1/configs/c.1/MaxPower

	sleep 1
	ln -s  /sys/kernel/config/usb_gadget/g1/functions/mass_storage.0 /sys/kernel/config/usb_gadget/g1/configs/c.1/f1
	echo "mass storage" > /sys/kernel/config/usb_gadget/g1/configs/c.1/strings/0x409/configuration
	echo 0x0000 > /sys/kernel/config/usb_gadget/g1/idProduct
	sleep 1
	echo $UDC > /sys/kernel/config/usb_gadget/g1/UDC
	
	;;
  stop)
	echo "none" > /sys/kernel/config/usb_gadget/g1/UDC
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
